pipeline {
    agent any
    tools {
        nodejs 'NodeJS'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/eudeyy85/TsheringEuden_02240368_DSO101_A1.git',
                    credentialsId: 'github-creds'
            }
        }
        stage('Install') {
            steps {
                dir('TsheringEuden_02240368_DSO101_A1/backend') {
                    bat 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Build done'
            }
        }
        stage('Test') {
            steps {
                dir('TsheringEuden_02240368_DSO101_A1/backend') {
                    bat 'npm test'
                }
            }
            post {
                always {
                    junit 'TsheringEuden_02240368_DSO101_A1/backend/junit.xml'
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs.'
        }
    }
}
