services:
  - type: web
    name: be-todolist-b
    runtime: docker
    dockerfilePath: ./TsheringEuden_02240368_DSO101_A1/backend/Dockerfile
    dockerContext: ./TsheringEuden_02240368_DSO101_A1/backend
    plan: free
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: fe-todolist-b
    runtime: docker
    dockerfilePath: ./TsheringEuden_02240368_DSO101_A1/frontend/Dockerfile
    dockerContext: ./TsheringEuden_02240368_DSO101_A1/frontend
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://be-todolist-b.onrender.com
        